### ISSUE TITLE
Love the idea - having a few issues getting it to work

### ISSUE THREAD

**Issue by jrowing** [geoffcarlier/BirdNET-Pixel#1]
Have run install but can't find how to run the software and it's not kicking out a webpage so I suspect an issue. I've tried the bash commands but getting "command not found"

**Comment by geoffcarlier** [comment]
Looks like I need to update the docs.   
Currently I use a wireguard VPN to the pixel for remote access, monitoring and maintenance.  The sync service kicks off periodically and copies mp3 files and the db to a raspberry pi.  This pi runs a birdnet-pi instance with most of its services switched off.  This reduces power consumption for the remote pixel which is the main problem of running this system all year round.  It also means I have the data if the pixel were to stop working in the field.

If you can tell me what you are doing I can comment on our install issues.

**Comment by jrowing** [comment]
Oh that's more awesome than I realised! I'll have another play and see if I can get it working

**Comment by jrowing** [comment]
> If you can tell me what you are doing I can comment on our install issues.

I have set up a few birdnet Pi's and stumbled across this project whilst looking for something to do with an old pixel. I was thinking of setting it up at home just because it's a device I have.

**Comment by jrowing** [comment]
Tried again and the install failed - I'll hunt through the logs and see what's going wrong.

**Comment by geoffcarlier** [comment]
I have added better notes for the install process, which will help, but there is a problem with the installer.  The system picks up the latest Birdnet-pi code, which has incompatibilities with some commands as the pixel uses slightly different versions and the pixel code has to deal with this.  I'll debug this hopefully in the next day or so.,

**Comment by geoffcarlier** [comment]
I have run through a fresh install which has completed successfully now.  Just provide some more details and I can help.

**Comment by jrowing** [comment]
Amazing - thank you!

**Comment by jrowing** [comment]
Working now! Great project!

**Comment by geoffcarlier** [comment]
I am really pleased this is working for you.  I will close this call.  
Just as an aside, I have a system running on a farm in Norfolk. I have definite recent recordings of Osprey and an Eagle Owl!
The only downside of the remote system is now I have to drive all the way up there as the plugin microphone has failed after a years recording.  Anyway enjoy!....

**Comment by jrowing** [comment]
That's awesome!
